/** Map FIFA 3-letter codes to flag-icons CSS country codes */
const FIFA_TO_FLAG = {
  ALG: 'dz',
  ANG: 'ao',
  ARG: 'ar',
  AUS: 'au',
  AUT: 'at',
  BEL: 'be',
  BIH: 'ba',
  BOL: 'bo',
  BRA: 'br',
  BUL: 'bg',
  CAN: 'ca',
  CHI: 'cl',
  CHN: 'cn',
  CIV: 'ci',
  CMR: 'cm',
  COD: 'cd',
  COL: 'co',
  CPV: 'cv',
  CRC: 'cr',
  CRO: 'hr',
  CUB: 'cu',
  CUW: 'cw',
  CZE: 'cz',
  DEI: 'id',
  DEN: 'dk',
  ECU: 'ec',
  EGY: 'eg',
  ENG: 'gb-eng',
  ESP: 'es',
  FRA: 'fr',
  FRG: 'de',
  GDR: 'de',
  GER: 'de',
  GHA: 'gh',
  GRE: 'gr',
  HAI: 'ht',
  HND: 'hn',
  HUN: 'hu',
  IRL: 'ie',
  IRN: 'ir',
  IRQ: 'iq',
  ISL: 'is',
  ISR: 'il',
  ITA: 'it',
  JAM: 'jm',
  JOR: 'jo',
  JPN: 'jp',
  KOR: 'kr',
  KSA: 'sa',
  KUW: 'kw',
  MAR: 'ma',
  MEX: 'mx',
  NED: 'nl',
  NGA: 'ng',
  NIR: 'gb-nir',
  NOR: 'no',
  NZL: 'nz',
  PAN: 'pa',
  PAR: 'py',
  PER: 'pe',
  POL: 'pl',
  POR: 'pt',
  PRK: 'kp',
  QAT: 'qa',
  ROU: 'ro',
  RSA: 'za',
  RUS: 'ru',
  SCO: 'gb-sct',
  SEN: 'sn',
  SLV: 'sv',
  SRB: 'rs',
  SUI: 'ch',
  SVK: 'sk',
  SVN: 'si',
  SWE: 'se',
  TCH: 'cz',
  TOG: 'tg',
  TRI: 'tt',
  TUN: 'tn',
  TUR: 'tr',
  UAE: 'ae',
  UKR: 'ua',
  URS: 'ru',
  URU: 'uy',
  USA: 'us',
  UZB: 'uz',
  WAL: 'gb-wls',
  YUG: 'rs',
  ZAI: 'cd',
};

export function getFlagClass(code) {
  const flagCode = FIFA_TO_FLAG[code];
  if (!flagCode) return null;
  return `fi fi-${flagCode}`;
}
